-- Throughput for the benchmark statements, from INFORMATION_SCHEMA (real time).
-- Run after both runs: $SNOW -f sql/08_report_throughput.sql
USE SCHEMA <% database %>.<% schema %>;
USE WAREHOUSE <% analysis_warehouse %>;

CREATE OR REPLACE TABLE BENCH_QUERY_TIMES AS
SELECT l.RUN_ID, l.STEP, l.N_ROWS, q.QUERY_ID, q.START_TIME, q.END_TIME,
       q.TOTAL_ELAPSED_TIME / 1000 AS ELAPSED_S,
       q.EXECUTION_TIME / 1000     AS EXECUTION_S,
       (q.QUEUED_PROVISIONING_TIME + q.QUEUED_OVERLOAD_TIME + q.QUEUED_REPAIR_TIME) / 1000 AS QUEUED_S,
       q.COMPILATION_TIME / 1000   AS COMPILATION_S
FROM RUN_LOG l
JOIN TABLE(INFORMATION_SCHEMA.QUERY_HISTORY_BY_WAREHOUSE(
       WAREHOUSE_NAME => 'DECIDER_BENCH_WH', RESULT_LIMIT => 10000)) q
  ON q.QUERY_ID = l.QUERY_ID;

-- Per stage, and decisions per second end to end (231 / summed statement time).
SELECT RUN_ID, STEP, N_ROWS, ROUND(ELAPSED_S, 1) AS ELAPSED_S, ROUND(QUEUED_S, 1) AS QUEUED_S,
       ROUND(N_ROWS / NULLIF(ELAPSED_S, 0), 2) AS ROWS_PER_S
FROM BENCH_QUERY_TIMES ORDER BY RUN_ID, START_TIME;

SELECT RUN_ID, ROUND(SUM(ELAPSED_S), 1) AS TOTAL_S, ROUND(231 / SUM(ELAPSED_S), 2) AS DECISIONS_PER_S
FROM BENCH_QUERY_TIMES WHERE RUN_ID IN ('run1', 'run2') GROUP BY RUN_ID ORDER BY RUN_ID;

-- GPU time per decision inside the container, by tier.
SELECT RUN_ID, TIER, COUNT(*) AS N,
       ROUND(MEDIAN(ELAPSED_MS)) AS P50_MS,
       ROUND(APPROX_PERCENTILE(ELAPSED_MS, 0.95)) AS P95_MS,
       ROUND(AVG(INPUT_TOKENS)) AS AVG_INPUT_TOKENS,
       ROUND(SUM(ELAPSED_MS) / 1000, 1) AS SUM_S
FROM DECIDER_DECISIONS WHERE RUN_ID IN ('run1', 'run2')
GROUP BY RUN_ID, TIER ORDER BY RUN_ID, ARRAY_POSITION(TIER::VARIANT, ['easy', 'standard', 'hard']);
