-- Teardown. Metering history in ACCOUNT_USAGE survives these drops, so
-- sql/09_cost_accounting.sql still works afterwards.
-- $SNOW -f sql/99_teardown.sql
USE SCHEMA <% database %>.<% schema %>;

DROP SERVICE IF EXISTS DECIDER_2B_SVC;
DROP SERVICE IF EXISTS DECIDER_2B_HTTP;
DROP SERVICE IF EXISTS DECIDER_2B_HTTP4;
DROP SERVICE IF EXISTS DTR_DECIDER_HTTP;
DROP SERVICE IF EXISTS DTR_ADJUDICATOR_APP;
-- Finished ML Jobs (train_dtr_job.py) stay listed as services until dropped; their names
-- are DTR_FINETUNE_<id> (SHOW SERVICES LIKE 'DTR_FINETUNE%'), e.g.
--   DROP SERVICE IF EXISTS DTR_FINETUNE_HSIKC4VP1W4J;
DROP STAGE IF EXISTS DTR_TRAIN_JOBS;
DROP COMPUTE POOL IF EXISTS DECIDER_BENCH_GPU_POOL;
DROP COMPUTE POOL IF EXISTS DECIDER_BENCH_GPU_POOL_S4;
DROP COMPUTE POOL IF EXISTS DECIDER_BENCH_BUILD_POOL;
DROP WAREHOUSE IF EXISTS DECIDER_BENCH_WH;
DROP EXTERNAL ACCESS INTEGRATION IF EXISTS DECIDER_BENCH_BUILD_EAI;
DROP NETWORK RULE IF EXISTS DECIDER_BENCH_BUILD_EGRESS;

-- Kept on purpose: the registered model (DECIDER_2B versions BATCH and SERVICE, about 3.8 GB each), the images
-- in DECIDER_BENCH_IMAGES (a redeploy can reuse them, though ours rebuilt the image), and the tables.
-- To remove everything:
--   DROP MODEL IF EXISTS DECIDER_2B;
--   DROP MODEL IF EXISTS DTR_DECIDER;
--   DROP IMAGE REPOSITORY IF EXISTS DECIDER_BENCH_IMAGES;
--   DROP SCHEMA IF EXISTS <% database %>.<% schema %>;

-- The DTR prototype's PAT network policy (created by hand in Snowsight, see README).
-- Run last, as ACCOUNTADMIN: once it is unset the PAT used by these scripts stops working.
--   ALTER USER <user> UNSET NETWORK_POLICY;
--   DROP NETWORK POLICY IF EXISTS DTR_PAT_POLICY;
--   DROP NETWORK RULE IF EXISTS DTR_ADMIN.NETWORK.DTR_PAT_ALLOWED_IPS;
--   DROP DATABASE IF EXISTS DTR_ADMIN;
